"""TaskRequest model — external-facing contract for task submission."""

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from smelt.schemas.enums import AgentType  # noqa: TC001


class TaskRequest(BaseModel):
    """Request to create and dispatch a new task.

    Args:
        task_id: UUID v4, generated by the caller (gateway or API).
        agent_type: Which agent pool should handle this task.
        payload_json: JSON string of the agent-specific payload. Deserialised
            by the orchestrator based on agent_type.
        trace_id: OpenTelemetry trace ID for distributed tracing.
        metadata: Optional key-value pairs for caller context.
    """

    model_config = ConfigDict(strict=True)

    task_id: str
    agent_type: AgentType
    payload_json: str
    trace_id: str
    metadata: dict[str, str] = Field(default_factory=dict)
