"""WorkItem generic model - the core message dispatched to agents."""

from __future__ import annotations

from datetime import datetime  # noqa: TC003
from typing import Generic, TypeVar

from pydantic import BaseModel, ConfigDict, Field

from smelt.schemas.enums import AgentType  # noqa: TC001

T = TypeVar("T", bound=BaseModel)


class WorkItem(BaseModel, Generic[T]):  # noqa: UP046
    """A unit of work dispatched to a specific agent type.

    Args:
        task_id: UUID v4 string, globally unique, generated by gateway.
        agent_type: Determines NATS subject and payload schema.
        payload: Per-agent typed payload (ResearchPayload, ReasoningPayload, etc.).
        trace_id: OpenTelemetry trace ID for distributed tracing.
        created_at: UTC timestamp of task creation.
        metadata: Optional key-value pairs for caller context.
    """

    model_config = ConfigDict(strict=True)

    task_id: str
    agent_type: AgentType
    payload: T
    trace_id: str
    created_at: datetime
    metadata: dict[str, str] = Field(default_factory=dict)
